[program:cloudflared]
command=/usr/local/bin/cloudflared tunnel run %(ENV_CLOUDFLARED_TUNNEL_ID)s
autostart=true
autorestart=true
startretries=5
startsecs=5
priority=3
user=ubuntu
environment=HOME="/home/ubuntu"
stdout_logfile=/var/log/cloudflared.log
stderr_logfile=/var/log/cloudflared.err
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
stdout_logfile_backups=3
stderr_logfile_backups=3
