[program:cloudflared]
command=/usr/local/bin/cloudflared tunnel run 2571f532-7790-4275-8bb4-33e0c20c64d6
autostart=true
autorestart=true
startretries=5
startsecs=5
priority=3
user=ubuntu
environment=HOME="/home/ubuntu"
stdout_logfile=/var/log/cloudflared.log
stderr_logfile=/var/log/cloudflared.err
stdout_logfile_maxbytes=5MB
stderr_logfile_maxbytes=5MB
